#!/bin/bash

#!/bin/bash

# Check if $XDG_CONFIG_HOME is set. If so, set config_dir to $XDG_CONFIG_HOME, else set it to $HOME/.config
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}"

# Check if config_dir/wallsync-dwm/config.conf exists; if not, error out
if [ ! -f "$config_dir/wallsync-dwm/config.conf" ]; then
    echo "$config_dir/wallsync-dwm/config.conf not found"
    exit 1
fi

# Set wallpaper_dir to the value of wallpaper_dir in config.conf
wallpaper_dir="$(grep wallpaper_dir "$config_dir/wallsync-dwm/config.conf" | cut -d'=' -f2)"

# Replace ~ with $HOME in wallpaper_dir
wallpaper_dir="${wallpaper_dir/#\~/$HOME}"

# If wallpaper_dir is empty, error out
if [ -z "$wallpaper_dir" ]; then
    echo "wallpaper_dir not set in $config_dir/wallsync-dwm/config.conf"
    exit 1
fi

# if xresources_file is set in config.conf, set it to xresources_file, else set it to ~/.Xresources
xresources_file="$(grep xresources_file "$config_dir/wallsync-dwm/config.conf" | cut -d'=' -f2)"
xresources_file="${xresources_file/#\~/$HOME}"
xresources_file="${xresources_file:-"$HOME/.Xresources"}"


# Check if $XDG_RUNTIME_DIR is set. If so, set tmp_dir to $XDG_RUNTIME_DIR, else set it to /run/user/$(id -u)
tmp_dir="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/wallsync-dwm"

# If tmp_dir does not exist, mkdir -p it with mode 700
if [ ! -d "$tmp_dir" ]; then
    mkdir -p -m 700 "$tmp_dir"
fi

current_wallpaper_file="$tmp_dir/current_wallpaper"
crop_wallpaper_file="$tmp_dir/cropped_wallpaper.jpg"

prepare_random_wallpaper;
crop_top "$(cat "$current_wallpaper_file")" "$crop_wallpaper_file";
gen_Xresources_from_wallpaper > $xresources_file;
feh --bg-fill $(cat $current_wallpaper_file);
apply_Xresources_to_dwm;
